require "rspec/core/rake_task"
require "standard/rake"
require_relative "spec/test_config"

task default: [:standard, :spec]

task spec: TestConfig.adapter_versions.map { |adapter_version| "spec:#{adapter_version}" }

TestConfig.adapter_versions.each do |adapter_version|
  namespace :spec do
    RSpec::Core::RakeTask.new(adapter_version) do |spec|
      TestConfig.current_adapter_version = adapter_version
      spec.rspec_opts = "--colour"
    end
  end
end

namespace :ci do
  namespace :coverage do
    desc "Collates all result sets generated by the CI runners"
    task :collate do
      require "simplecov"
      SimpleCov.collate Dir["coverage-resultsets/coverage-*/.resultset.json"] do
        enable_coverage :branch
        formatter SimpleCov::Formatter::SimpleFormatter
      end
    end
  end
end
