sqlite:
  adapter: sqlite3
  database: ":memory:"
mysql9.5:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13316
mysql9.4:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13317
mysql9.3:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13318
mysql9.2:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13319
mysql9.1:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13320
mysql9.0:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13321
mysql8.4:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13322
mysql8.3:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13323
mysql8.2:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13324
mysql8.1:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13325
mysql8.0:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13326
mysql5.7:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13327
mysql5.6:
  adapter: mysql2
  host: 127.0.0.1
  database: temping_test
  username: root
  password:
  port: 13328
postgresql18:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15442
postgresql17:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15443
postgresql16:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15444
postgresql15:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15445
postgresql14:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15446
postgresql13:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15447
postgresql12:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15448
postgresql11:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15449
postgresql10:
  adapter: postgresql
  host: 127.0.0.1
  database: temping_test
  username: postgres
  password: password
  port: 15450
